SELECT 
    A.PRODUCT_ID, 
    A.PRODUCT_NAME, 
    SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A
JOIN FOOD_ORDER B 
    ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE TRUNC(B.PRODUCE_DATE, 'MM') = TO_DATE('2022-05', 'YYYY-MM')
GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC;